apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: asia.gcr.io/poc-innovation-iot/training-kube/galgal-consumer-app
    newTag: v1.4

configMapGenerator:
  - behavior: merge
    envs:
      - configs/config.env
    name: galgal-consumer-app-configmap-env
  - behavior: merge
    files:
      - configs/config.yaml
    name: galgal-consumer-app-configmap-file

secretGenerator:
  - behavior: merge
    envs:
      - secrets/secret.env
    name: galgal-consumer-app-secret-env

patchesStrategicMerge:
  - patches/set_resources.yaml
