apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: asia.gcr.io/poc-innovation-iot/galgal-user-consumer
    newTag: 7d3e9b91
# - name: asia.gcr.io/poc-innovation-iot/training-galgal/galgal-user-consumer
#   newTag: v1.4

configMapGenerator:
  - behavior: merge
    envs:
      - configs/config.env
    name: galgal-user-consumer-configmap-env
  - behavior: merge
    files:
      - configs/config.yaml
    name: galgal-user-consumer-configmap-file

secretGenerator:
  - behavior: merge
    envs:
      - secrets/secret.env
    name: galgal-user-consumer-secret-env

patchesStrategicMerge:
  - patches/set_resources.yaml
