# don't forget to update config.model
environment: local

app:
  name: gal-consumer

server:
  port: 8080
  timeout: 15

log:
  environment: production
  level: info
  format: json

postgres:
  host: 172.28.240.42
  port: 5432
  db-name: galgal-hw3
  db-timezone: Asia/Bangkok
  db-ssl: disable

redis:
  address: 172.28.241.3:6379
  password:
  database: 0

kafka:
  address:
    - kafka.poc.internal:9092
  topic: gal-topic
  consume-group: consumer-group

user-list-key: GALGAL_USER_LIST
