apiVersion: v1
kind: Service
metadata:
  name: galgal-user-consumer
  labels:
    app.kubernetes.io/name: galgal-user-consumer
    app.kubernetes.io/instance: galgal-user-consumer
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: galgal-user-consumer
    app.kubernetes.io/instance: galgal-user-consumer
